apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-web
  namespace: NAMESPACE
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: HOSTNAME
    http:
      paths:
      - path: /
        backend:
          serviceName: web-svc
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: NAMESPACE
spec:
  selector:
    app: demo-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-web
  namespace: NAMESPACE
  labels:
    app: exchange-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-web
  template:
    metadata:
      labels:
        app: exchange-web
    spec:
      containers:
      - name: exchange-web
        image: ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/exchange-web:IMAGEVERSION
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: API_HOST
          value: "http://api-svc:80"