apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: NAMESPACE
spec:
  selector:
    app: exchange-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-api
  namespace: NAMESPACE
  labels:
    app: exchange-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-api
  template:
    metadata:
      labels:
        app: exchange-api
    spec:
      containers:
      - name: exchange-api
        image: ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/exchange-api:IMAGEVERSION
        env:
        - name: PORT
          value: "80"
        - name: DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB
        ports:
        - containerPort: 80